### ISSUE TITLE
结果参数怎么看

### ISSUE THREAD

**Issue by 1456214718** [weijun88/WeakPolyp#4]
我复现了您的代码，我不太能看懂评价，跑完后就只有log和model.pth，结果在log里面看吗？

**Comment by weijun-arc** [comment]
是的，log文件里面测试了不同epoch下模型的性能

**Comment by 1456214718** [comment]
我还是有个疑问，就是我跑完所有之后，发现我就只能看到easytesting和hardtesting的评估数据，看不到train的评估数据，想问怎么看到？

**Comment by weijun-arc** [comment]
代码里面没有做train的评估，只评估了两个测试集
